### PR TITLE
LXL-2413 super collection

### PR DESCRIPTION
**Pull request by olovy**
Pending a better name than 'super collection' here is the implementation of 'super collection' aka supersigel.

### CODE REVIEW

**Comment by olovy** [comment]
Jenkins pipeline is failing sporadically...
[run6](https://jenkins.kb.se/blue/organizations/jenkins/Libris%2Fxl_auth-multibranch/detail/feature%2Flxl-2413/6/pipeline) vs [run5](https://jenkins.kb.se/blue/organizations/jenkins/Libris%2Fxl_auth-multibranch/detail/feature%2Flxl-2413/5/pipeline)

**Comment by mxtthias** [comment]
This seems reasonable enough, but I want us to limit who can set this new permission to administrators (`User.is_admin`). Hide the input field from non-admins and check that the user doesn't manipulate the form.

The Jenkins pipeline has been acting up the last couple of times, no idea what's causing it. :/

**Comment by olovy** [comment]
> This seems reasonable enough, but I want us to limit who can set this new permission to administrators (`User.is_admin`). Hide the input field from non-admins and check that the user doesn't manipulate the form.

Only administrators can get and post the collections edit form.
[collections/views.py:L68](https://github.com/libris/xl_auth/blob/80500fcc5581b574b030094b3442c87cbce8a614/xl_auth/collection/views.py#L68)
[collections/forms.py:L72](https://github.com/libris/xl_auth/blob/80500fcc5581b574b030094b3442c87cbce8a614/xl_auth/collection/forms.py#L72)

**Comment by olovy** [comment]
Do this as a new user-collection permission instead

**Pull request closed without merging**
