### PR TITLE
Feature/update dependencies

### PR DESCRIPTION
**Pull request by lrosenstrom**
Update dependencies and fix security warnings 

Running with PostgreSQL 13.3, python 3.6 and node 14 at http://login-dev.libris.kb.se

TODO: 
*fix feature branch CI (probably just need to upgrade node version on jenkins slave): https://jenkins.kb.se/view/Libris/job/Libris/job/xl_auth-multibranch/job/feature%252Fupdate-dependencies/
*automatic deploy of dev branch to http://login-dev.libris.kb.se

### CODE REVIEW

**Review by andersju — CHANGES_REQUESTED** [review]
Following the steps in the README everything works fine until I get to the flask steps (`flask db upgrade` / `run` / ..):
```
...
FileNotFoundError: [Errno 2] No such file or directory: '/home/andersju/lxl/xl_auth/xl_auth/webpack/manifest.json'
...
RuntimeError: Flask-Webpack requires 'WEBPACK_MANIFEST_PATH' to be set and it must point to a valid json file.
```

**Comment by lrosenstrom** [comment]
> Following the steps in the README everything works fine until I get to the flask steps (`flask db upgrade` / `run` / ..):
> 
> ```
> ...
> FileNotFoundError: [Errno 2] No such file or directory: '/home/andersju/lxl/xl_auth/xl_auth/webpack/manifest.json'
> ...
> RuntimeError: Flask-Webpack requires 'WEBPACK_MANIFEST_PATH' to be set and it must point to a valid json file.
> ```

Good catch! The plugin for generating the manifest.json is deprecated and has been replaced by https://github.com/nickjj/flask-static-digest. The template flask app ("Cookiecutter-flask" https://github.com/cookiecutter-flask) that xl_auth once upon a time was built on has some clues on how to do this migration (https://github.com/cookiecutter-flask/cookiecutter-flask/commit/3e53bdb824c057a64331e6fa034cae54dc7d3b0d). I did the necessary steps that I think are relevant, but to be honest I'm fumbling a bit in the darkness when it comes to this whole digesting-bundling-manifesting-business.

**Review by andersju — APPROVED** [review]
:ship:

**Comment by jannistsiroyannis** [comment]
:trophy:

**Pull request merged**
