### PR TITLE
Feature/cookiecutter-flask Template

### LINKED ISSUE #2: Use more suitable project template
Current cookiecutter template, https://github.com/ardydedase/cookiecutter-pypackage.git, lacks many of the things required to create a BibDB replacement. Instead of extending it with static files, proper application factory, CLI, endpoint tests et cetera, a dedicated Flask cookiecutter template should be put to use, e.g. [cookiecutter-flask](https://github.com/sloria/cookiecutter-flask).

### PR DESCRIPTION
**Pull request by mblomdahl**
#### This fixes #2— and a bunch other stuff —by ...

* [x] replacing previous cookiecutter-pyproject template with [cookiecutter-flask](https://github.com/sloria/cookiecutter-flask)
* [x] refactoring  included tests into a more flat structure that should better serve `xl_auth` purposes
* [x] replaced builtin Python 2/3 compatibility approach with future imports everywhere
* [x] correcting all flake8 linter errors
* [x] added a couple extra test cases to pytest in test_package.py (just to try it out)
* [x] bumped minor version to 0.2.0

#### Things left to do:
* [ ] Found an interesting open issue in template for adding envvar configs, so I opened issue #3 here for backporting a solution when available

#### Proof that it works:

```bash
mkdir ~/xl_auth_test && cd ~/xl_auth_test
git clone https://github.com/libris/xl_auth.git -b feature/flask-template
cd xl_auth/
npm install
npm run build
virtualenv venv --python=python3.6  # Python 2.7 works equally
source venv/bin/activate
pip install -r requirements/dev.txt  # Install all requirements for lint/test/run
export FLASK_DEBUG=1
export FLASK_APP=autoapp.py 
flask lint  # Should report no flake8 violations
flask test
flask db upgrade  # Executes initial migration on debug SQLite DB
flask run
```

After this, you should be able to browse to http://localhost:5000, register an account, login and logout again.

screen shot 2017-09-11 at 2 34 36 pm

### CODE REVIEW

**Comment by mblomdahl** [comment]
P.S. @klngwll @simonalmliljevall I don't know how much opinions you might have on this matter.. But since it involves a bunch of node/frontend stuff I thought it would be a good idea to invite feedback on this approach! D.S.

**Comment by mblomdahl** [comment]
@oBlissing found a bug in the *Proof that it works* code sample, so I just updated PR description to read
```bash
/.../
export FLASK_DEBUG=1
export FLASK_APP=autoapp.py 
flask lint  # Should report no flake8 violations
flask test
/.../
```

instead of the broken
```bash
flask lint  # Should report no flake8 violations
flask test
export FLASK_DEBUG=1
export FLASK_APP=autoapp.py 
```

If `FLASK_APP` path is not exported, Flask CLI won't attach properly to our application.

**Comment by mxtthias** [comment]
Got (only) this warning when following the instructions:

```
$ npm install
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
```

Does it behave differently on OSX?

**Comment by mxtthias** [comment]
I'm getting `ImportError: No module named flask_login` on both `flask lint` and `flask test`. If I start a Python interpreter and run `import flask_login`, it works. Any ideas? I ran the two export commands before running the flask commands.

**Comment by mblomdahl** [comment]
@mxtthias Thank's for trying it out! Very interesting error you get.

> I'm getting `ImportError: No module named flask_login` on both `flask lint` and `flask test`. If I start a Python interpreter and run `import flask_login`, it works. Any ideas? I ran the two export commands before running the flask commands.

Super odd... Works on Ola's MacBook, CentOS 7 boxes and my partner's Fedora 26. Never tried on Debian though. :/ If could get a stacktrace with the `ImportError`, could you post it? Also, from inside the venv you're experiencing this, in the repo root dir, could you post the output of ...

```bash
env && python --version && pip --version && pip freeze
```

> Got (only) this warning when following the instructions:
>
>     $ npm install
>     npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
>     npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
>
> Does it behave differently on OSX?

Yep! It's some kind of package used for detecting file system events on macOS, no warnings there. But for Linux it uses some built-in mechanism methinks, so the package is not applicable there.

**Comment by mblomdahl** [comment]
@mxtthias Doesn't seem like the odd error is about Debian... I tried the following, started one py27 and one py36 Debian in different terminals, then ran the install steps:

Terminal 1:
```bash
docker run -it python:3.6-stretch bash
```

Terminal 2:
```bash
docker run -it python:2.7-stretch bash
```

In both terminals, copy-pasted in ...
```bash

curl -sL https://deb.nodesource.com/setup_8.x | bash - \
    && apt-get install -y nodejs \
    && apt-get install -y build-essential \
    && pip install virtualenv \
    && mkdir ~/xl_auth_test && cd ~/xl_auth_test \
    && git clone https://github.com/libris/xl_auth.git -b feature/flask-template \
    && cd xl_auth/ \
    && npm install \
    && npm run build \
    && virtualenv venv \
    && source venv/bin/activate \
    && pip install -r requirements/dev.txt \
    && export FLASK_DEBUG=1 \
    && export FLASK_APP=autoapp.py \
    && flask lint \
    && flask test \
    && flask db upgrade \
    && flask run

```

No errors. Again, odd!

**Pull request merged**
